#!/bin/sh

. /etc/functions

# Bring all the nics up
for nic in $(get_nics); do
  ifconfig ${nic} up
done

# Busy poll on a link being detected
while [ "$(get_running_nic)" = '' ]; do
  sleep 1
done

# Busy poll on DHCP success.
while ! udhcpc -n -v -i $(get_running_nic); do
  sleep 1
done

mkdir /newlib
cp /lib/libz.so.1 /newlib/.

cd /
wget-measure.sh 8 http://keylime-server/keylime.tar.gz
tar -xvzf keylime.tar.gz

if [ ! -x /keylime_node ]; then
  recovery 'Keylime overlay not found?'
fi

/keylime_node &
KEYLIME_PID=$!

wait $KEYLIME_PID
recovery 'Keylime-node failed unexpectedly'
