#!/bin/sh
# Bring up the x230's NIC, get a DHCP address, and invoke keylime

. /etc/functions

udhcpc -n -v

mkdir /newlib
cp /lib/libz.so.1 /newlib/.

cd /
wget-measure.sh 8 http://keylime-server/keylime.tar.gz
tar -xvzf keylime.tar.gz

if [ ! -x /keylime_node ]; then
  recovery 'Keylime overlay not found?'
fi

/keylime_node &
KEYLIME_PID=$!

wait $KEYLIME_PID
recovery 'Keylime-node failed unexpectedly'
